---
title: "R Notebook"
output: html_notebook
---


```{r}
dfTrain = read.table("alturasEntre.txt", header = F)
dfTest = read.table("alturasPrueba.txt", header = F)
colnames(dfTrain) = c("altura","sexo")
colnames(dfTest) = c("altura","sexo")
```
```{r}
library(ggplot2)
```
```{r}
p <- ggplot(dfTrain, aes(y=as.factor(sexo), x=altura, fill=sexo)) + 
  geom_violin()
p
```

```{r}
alturasMenos165 = abs(dfTrain$altura - 165)
alturasMenos175 = abs(dfTrain$altura - 175)

```
```{r}
dfTrain$alt165 = alturasMenos165
dfTrain$alt175 = alturasMenos175
```

```{r}
dfT165 = dfTrain[order(dfTrain$alt165),]
dfT175 = dfTrain[order(dfTrain$alt175),]
```
```{r}
mean(dfT165$sexo[1:10])<1/2
mean(dfT175$sexo[1:10])<1/2
```
Entonces por voto de mayoria al de 165 sera clasificado mujer y al 175 como hombre
```{r}
promediosMoviles = function(A, S, alturaAestimar, h){
  df = data.frame(A,S)
  df2 = df[df$A > alturaAestimar-h & df$A < alturaAestimar+h ,]
  #print(df)
  if(mean(df2$S)>1/2 ){
    return(1)
  }
  return(0)
}
```

```{r}
promediosMoviles(dfTrain$altura, dfTrain$sexo, 170.5, 2.5)
```
```{r}
ClasificoVecinos =function(A,S,a,k){
  alturasMenosA = abs(A - a)
  dff = data.frame(S, alturasMenosA)
  dff = dff[order(dff$alturasMenosA),]
  if(mean(dff$S[1:k])<1/2){
    return(0)
  }
  return(1)

}
```

```{r}
ClasificoVecinos(dfTrain$altura, dfTrain$sexo, 166, 10)
```
```{r}
generarColumnaPrediccionesVecinos = function(dfTrain, dfEval, k){
  sexoPredicho = c()
  for (i in (1: length(dfEval$altura))){
    sexoPredicho[i] = ClasificoVecinos(dfTrain$altura, dfTrain$sexo, (dfEval$altura[i]), k)
  }
  #df = cbind(df, sexoPredicho)
  return(sexoPredicho)
}
```
```{r}
generarColumnaPrediccionesPromediosMoviles = function(dfTrain, dfEval , h){
  sexoPredicho = c()
  for (i in (1: length(dfEval$altura))){
    sexoPredicho[i] = promediosMoviles(dfTrain$altura, dfTrain$sexo, (dfEval$altura[i]), h)
  }
  return(sexoPredicho)
}
```

```{r}
vals = c(1:50)
res = c()
for(i in 1:length(vals)){
  aux = generarColumnaPrediccionesVecinos(dfTrain, dfTrain, vals[i])
  res[i] = sum(abs(dfTest$sexo - aux))
}
```
```{r}
valsH = c(1:30)
resP = c()
for(i in 1:length(valsH)){
  aux = generarColumnaPrediccionesPromediosMoviles(dfTrain, dfTrain, valsH[i])
  resP[i] = sum(abs(dfTest$sexo - aux))
}
```
```{r}
plot(vals,res, log="", col="red")
```

```{r}
#
plot(valsH, resP, col="blue")
```
```{r}
resP
```

```{r}
bws = c(0.1,0.5,1,2,3,4,5,6,10,15,20,30,40,50,80)
des = ksmooth(dfTrain$altura, dfTrain$sexo, bandwidth=2, x.points = dfTrain$altura)
```

```{r}
plot(des)
```
```{r}
density(x, )
```

