---
title: "R Notebook"
output: html_notebook
---

```{r}
bootstrap1 = function(muestra, cantResampleo, funcionEstimadora){
  estimadores = rep(0, cantResampleo)
  for (i in (1:cantResampleo)){
    muestraNueva = sample(muestra, length(muestra), replace = T)
    estimadores[i] = funcionEstimadora(muestraNueva)
  }
  return(estimadores)
}
```
```{r}
standarError = function(muestra){
  media = mean(muestra)
  sumaCuadrada = 0
  for (i in (1:length(muestra))){
    sumaCuadrada = sumaCuadrada + (muestra[i]-media)^2
  }
  sumaCuadrada = sumaCuadrada/length(muestra)
  return(sqrt(sumaCuadrada))
}
```

```{r}
muestra = c(1,0.2,0.3,0.4,0.5,0.6,0.7)
estimadores = bootstrap1(muestra, 1000, mean)
```

```{r}
sd(estimadores)
sdTita = standarError(estimadores)
```
```{r}
estMomentoFuncion5 = function(muestra){
  a = 1/mean(muestra) - 1
  return(1/a)
}
```
```{r}
tita = estMomentoFuncion5(estimadores)
```

```{r}
#METODO 1
c(tita + qnorm(0.025) * sdTita, tita - qnorm(0.025) * sdTita)
```

```{r}
#METODO 2
c(quantile(estimadores,0.025),quantile(estimadores,0.975))
```

