---
title: "R Notebook"
output: html_notebook
---
```{r}
crearDataset = function (cantVariables, cantObservaciones, parametro=1){
  df = data.frame(1:cantObservaciones)
  colnames(df)=c("tipo")
  nom = c("tipo")
  for (i in 1:cantVariables) {
    df[i+1] = rnorm(cantObservaciones)
    nom[i+1]=paste("var",i,sep = "")
  }
  colnames(df)=nom
  df$tipo=rep(c(0,1,2),cantObservaciones/3)
  return(df)
}
```
```{r}
maximaCorrelacion = function (cantVariables, cantObservaciones, parametro=1){
  res <- cor(df)
  diag(res) = 0
  resMod = abs(res)
  cuales = which.max(abs(res))
  return(c(max(res), cuales) )
}
```
```{r}
dfdiferencia = function(df){
  df3 = (df[df$tipo==2,] - df[df$tipo==1,])
  df3$tipo = 0
return(df3)
}
```

```{r}
variableMasSignificativaTtest = function(df){
  return(c(max(apply(df, 2, mean)), max(apply(df, 2, sd))))
}
```
```{r}
variablesSignificativas= function(df, dfdif, nivelConfianza){
  i = 1
  significativas = c()
  cuanSignificativas = c()
  for (var in 2:ncol(df)) {
    testcito = t.test(
    x           = df[,var],
    y           = dfdif[,var],
    alternative = "two.sided",
    mu          = 0,
    var.equal   = TRUE,
    conf.level  = nivelConfianza
  )
  #¨print(testcito$p.value)
  if(testcito$p.value<(1-nivelConfianza)){
    significativas[i]=var
    cuanSignificativas[i] = testcito$p.value
    i = i+1
    }
  }
  dfsig = data.frame(significativas)
  dfsig["pvalor"] = cuanSignificativas
  colnames(dfsig) = c("variablesSignificativas", "pValor")
  return(dfsig)
}
```
```{r}
realizar1exp = function(nVar, nObs, nivelConfianza){
  df= crearDataset(cantVar, cantObs)
  df1 = df[df$tipo==1,]
  df2 = df[df$tipo==2,]
  s =variablesSignificativas(df1, df2, nivelConfianza)
  return(length(s$variablesSignificativas))
  
}
```
¨
```{r}
realizarKexperimentos = function(nVar, nObs, nivelConfianza, k){
  cantVarSig = 0
  for (i in 1:k) {
    cantVarSig = cantVarSig + realizar1exp(nVar, nObs, nivelConfianza)
  }
  return(cantVarSig/k)
  }
```
```{r}
cantVar = 100
cantObs = 120
nivelConfianza = 0.99
k = 50
realizarKexperimentos(cantVar,cantObs, nivelConfianza, k)

```


```{r}
df= crearDataset(cantVar, cantObs)
dfdif = dfdiferencia(df)
df1 = df[df$tipo==1,]
df2 = df[df$tipo==2,]
variableMasSignificativaTtest(dfdif)
#s = maximaCorrelacion(df)
```

```{r}
s =variablesSignificativas(df1, df2, nivelConfianza)
s
```

```{r}
shapiro.test(dfdif$var1)
```


```{r}
estimar = function(){
  vec = rgamma(10000,2,3)
  vecCuadrado = vec ** 2
  
  xnsum = sum(vec)
  xnCuadradosum = sum(vecCuadrado)
  promedioDeSumaCuadrado = (1/length(vec)) * sum(vec)**2
  
  lamdaMomentos = xnsum / (xnCuadradosum - promedioDeSumaCuadrado)
  alphaMomentos = xnsum * lamda / length(vec) 
  return(c(alphaMomentos, lamdaMomentos))
}
```
```{r}
lamdas = c()
alphas = c()
for (i in 1:1000) {
  valores = estimar()
  lamdas[i] = valores[2]
  alphas[i] = valores[1]
}
```
```{r}
plot(alphas, lamdas)
points(median(alphas), median(lamdas), col='red')
```

```{r}
newtonRaph = function (puntoInicial, stepMinimo, maxIteraciones, funcion, funcionDerivada, vec){
  xViejo = puntoInicial + 5 + stepMinimo
  xNuevo = puntoInicial 
  iteracion = 0
  diferencia = abs(xViejo-xNuevo)
  while(iteracion<maxIteraciones ){ #& diferencia>stepMinimo
    xViejo = xNuevo
    xNuevo = xNuevo - funcion(vec, xNuevo)/funcionDerivada(vec, xNuevo)
    diferencia = abs(xViejo-xNuevo)
    iteracion = iteracion + 1
  }
  return(xNuevo)
}
```

```{r}
funcionLamda = function(vec, lamda){
  suma = 0
  xnBarra = mean(vec)
  for (i in 1:length(vec)) {
    suma = suma + log(vec[i]) - log(xnBarra/lamda) - digamma(lamda)
  }
  return(suma)
}

funcionPrimaLamda = function(vec, lamda){
  n = length(vec)
  suma = n / (mean(vec) * lamda) -  n * trigamma(lamda)
  return(suma)
}
```
```{r}
vec = rgamma(10000,2,3)
newtonRaph(3.1, 0.001, 1000, funcionLamda, funcionPrimaLamda, vec) # ?????????????????????????????????????
```
```{r}
funcionLamda(vec, 3)
funcionPrimaLamda(vec, 3)



